# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5728a5572bb0b0e3a2f8578aa0b0803b65c4c29ff96b3e99e7effa9a02eedeacf79d99f458ba8dcd861843f2067b8027ef5222422d4a73abd6afff9e41a93ab0

test:
  secret_key_base: fdb49e5ab86a3e7e2f17f7a3a3a668c387adee2c22db8385d599fe605b2417b95687e2e529c8030991416bd6992c678159f156b4d885805d5ca08774c5b71af7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
